package utility

import (
	"bytes"

	"github.com/mh-cbon/emd/emd"
)

type Readme struct {
	Title       string
	Description string
	Watermark   bool
}

func (r Readme) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"Title":       r.Title,
		"Description": r.Description,
		"Watermark":   r.Watermark,
	}
}

func (readme Readme) Render() ([]byte, error) {
	gen := emd.NewGenerator()
	gen.AddTemplate(README_TEMPLATE)
	gen.SetDataMap(readme.ToMap())

	var rendered bytes.Buffer
	if err := gen.Execute(&rendered); err != nil {
		return []byte{}, err
	}

	return rendered.Bytes(), nil
}

const README_TEMPLATE = `# {{ .Title }}

{{ .Description }}

{{ if .Watermark }}
*README generated by [readcli](https://github.com/Tch1b0/readcli)*
{{ end }}`
