package utility

import (
	"bytes"
	"strings"

	"github.com/mh-cbon/emd/emd"
)

type Readme struct {
	Title         string
	Description   string
	RepositoryURL string
	Watermark     bool
}

func (r Readme) ToMap() map[string]interface{} {
	splittedRepo := strings.Split(r.RepositoryURL, "/")
	username := splittedRepo[len(splittedRepo)-2]
	repoName := splittedRepo[len(splittedRepo)-1]
	return map[string]interface{}{
		"Title":          r.Title,
		"Description":    r.Description,
		"RepositoryURL":  r.RepositoryURL,
		"Username":       username,
		"RepositoryName": repoName,
		"Watermark":      r.Watermark,
	}
}

func (readme Readme) Render() ([]byte, error) {
	gen := emd.NewGenerator()
	gen.AddTemplate(README_TEMPLATE)
	gen.SetDataMap(readme.ToMap())

	var rendered bytes.Buffer
	if err := gen.Execute(&rendered); err != nil {
		return []byte{}, err
	}

	return rendered.Bytes(), nil
}

const README_TEMPLATE = `# {{ .Title }}

![shield](https://img.shields.io/github/license/{{ .Username }}/{{ .RepositoryName }})

{{ .Description }}

{{ if .Watermark }}
*README generated by [readcli](https://github.com/Tch1b0/readcli)*
{{ end }}`
